### ISSUE TITLE
如何在callback中把$response->body赋值给外部变量

### ISSUE THREAD

**Issue by xiucaiwu** [sinacms/MultiHttp#6]
$data = [];
        
$mr  = MultiRequest::create();

$rtn = $mr->add('GET', 'http://www.baidu.com', array(), array(
	'timeout' => 2,
	'callback' => function (Response $response) use ($data) {
		$data['baidu'] = json_decode($response->body);
	}
))->sendAll();
var_dump($data);

打印结果为空

**Comment by xiucaiwu** [comment]
经尝试,在add的第三个参数中可以接受外部变量

**Comment by 974480274** [comment]
@xiucaiwu add中添加中接受外部变量怎么样的，我也遇到了这个body值获取不到，现在还不知道怎么获取到。。

**Comment by xiucaiwu** [comment]
`$mr->add('GET', $c2cUrl, $key, array(
                'timeout' => 2,
                'callback' => function (Response $response) use ($key) {
                    $_ENV[$key]['price'] = $response->body;
                }
            ))->add('GET', $buyinfo, $key, array(
                'timeout' => 2,
                'callback' => function (Response $response) use ($key) {
                    $_ENV[$key]['buyinfo'] = $response->body;
                }
            ))->add('GET', $sellinfo, $key, array(
                'timeout' => 2,
                'callback' => function (Response $response) use ($key) {
                    $_ENV[$key]['sellinfo'] = $response->body;
                }
            ));
        }
        $mr->sendAll();`
用超全局变量保存你要的值
